#!/usr/bin/env bash
set -ex

HERE=$(realpath  "$(dirname $0)")
. $HERE/common

aws ecr get-login-password | docker login --username AWS --password-stdin $URI

docker tag $IMAGE_NAME:latest $URI/$IMAGE_NAME:latest
docker push $URI/$IMAGE_NAME:latest
